### PR TITLE
Enable Versioning by tag

### PR DESCRIPTION
**Pull request by eneskuluk**
Adds versioning support according to tag. Also move build options to github actions side rather than pyproject.toml.

### CODE REVIEW

**Review by nalinigans — CHANGES_REQUESTED** [review]
LGTM, but there is a failure while publishing. Can that be fixed? Or what is the reason/\?

**Comment by eneskuluk** [comment]
I just used the same version tag that was already in testpypi to avoid publishing the same thing again. It was intended to fail, meaning it was able to get 0.0.9.3 from v0.0.9.3.test tag.

**Comment by eneskuluk** [comment]
I noticed one bug though, I will send one more commit to fix it. Currently it doesn't use the tag version number for sdist. I will add that as well.

**Review by nalinigans — APPROVED** [review]
LGTM. See the annotation warnings here - https://github.com/GenomicsDB/GenomicsDB-Python/actions/runs/6937502067. We should probably upgrade to Trusted Publishing as suggested. This could be done as part of another PR. See #39. Thanks.

**Comment by eneskuluk** [comment]
> LGTM. See the annotation warnings here - https://github.com/GenomicsDB/GenomicsDB-Python/actions/runs/6937502067. We should probably upgrade to Trusted Publishing as suggested. This could be done as part of another PR. See #39. Thanks.

Sure, I'll take a look at it.

**Pull request merged**
