### PR TITLE
Add simple example GenomicsDB query script

### PR DESCRIPTION
**Pull request by nalinigans**
There is a `run.sh` script and a `README.md`, hopefully all self-explanatory.

### CODE REVIEW

**Comment by nalinigans** [comment]
@mlathara should I also zip up the files and keep it on GitHub?

**Comment by mlathara** [comment]
I don't think we need to zip up the file. This looks good to me. One request, and one question:

- I should've mentioned that the request from UCLA was to a) enable querying some genomic region for all/most all samples b) enable querying all genomic regions from some subset of samples. So we'll need to read in the callset file as well, and have support for regions/sample names to be specified (both could be optional). Hopefully that's not too much more work.
- Any indication on whether performance/memory was affected when using dataframe versus json or something else? I suppose the bypass optimization is really the much bigger hammer, but was curious

**Comment by nalinigans** [comment]
> Any indication on whether performance/memory was affected when using dataframe versus json or something else? I suppose the bypass optimization is really the much bigger hammer, but was curious

For a workspace associated with the TCGA 1000 dataset and for the query with these arguments `-L 1:30000000-35000000 -L 2:31374500-31374545 -f 'resolve(GT, REF, ALT) &= "T/T"'`, the json was written out as a json file, that is did not write it out as a csv.

1. df.to_csv : **71.32u**ser **10.07**system 1:18.51elapsed 103%CPU (0avgtext+0avgdata **624472**maxresident)k
2. df.to_csv with bypass: **67.55**user **6.07**system 1:08.40elapsed 107%CPU (0avgtext+0avgdata **600980**maxresident)k
3. json:  **68.58**user **10.34**system 1:15.76elapsed 104%CPU (0avgtext+0avgdata **598856**maxresident)k
4. json with bypass : **57.51**user **5.91s**ystem 0:58.17elapsed 109%CPU (0avgtext+0avgdata **533112**maxresident)k

**Comment by nalinigans** [comment]
> I should've mentioned that the request from UCLA was to a) enable querying some genomic region for all/most all samples b) enable querying all genomic regions from some subset of samples. So we'll need to read in the callset file as well, and have support for regions/sample names to be specified (both could be optional). Hopefully that's not too much more work.

Will work on this.

**Comment by nalinigans** [comment]
@mlathara, anything else left to do in this PR for now?

**Review by mlathara — APPROVED** [review]
nope, lgtm

**Pull request merged**
